### ISSUE TITLE
planned growth

### ISSUE THREAD

**Issue by alku50** [RealismusModding/FS19_RM_PlantableSpruceTrees#1]
Thanks for the mod. I did build a big tree plantation on Nebraska Lands with seasons. What growth rate do I expect from your plantable spruce trees?  Thanks for the answer.

**Comment by reallogger** [comment]
The growth rate is the same as for the vanilla fir trees. With Seasons that is 5 years from planted to fully grown.

**Comment by alku50** [comment]
Thanks for the quick answer. Needs a lot of patience.  :-)

**Comment by reallogger** [comment]
Remember that you can cut after two years to give some intermediate income :-) And it might be better financially to clear-cut after four instead of waiting until fully grown at five years.

I'll close this comment now.
